### ISSUE TITLE
Add pyro-ppl to conda-forge

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/pyro#1764]
Does everyone agree if I submit a PR to add pyro-ppl to conda-forge [with the receipt](https://gist.github.com/fehiepsi/1e6c26dd30144e413f1c412179bd53b8)?

About maintaining, whenever we have a new version, conda-forge will automatically make a PR with updated version and updated sha256. The only thing we need to do is merging that PR if everything is fine. If we change requirements in future versions, we will need to submit a PR to change the requirements section of that recipe.

If everyone is fine with it, then there are two things we'll need to change:
+ recipe-maintainers: we need one or two more persons
+ [source file for 0.3.1](https://github.com/pyro-ppl/pyro/archive/0.3.1.tar.gz) needs to be updated: currently I get the error as in https://github.com/pyro-ppl/pyro/issues/1759 when trying to install from that source file.

**Comment by fritzo** [comment]
This seems like unnecessary overhead. We have limited resources on the Pyro team, and I feel those resources are better spent on documentation, design, and support. Also this would add extra friction to the already high-friction release process, and in response we would react by releasing less frequently.

**Comment by fehiepsi** [comment]
I guess this just adds a tiny overhead because all we will do is to press a merge button when receives a notification from conda-forge. But I'll test how it will go first.

**Comment by fritzo** [comment]
@fehiepsi The kind of overhead I'm talking about is developer resources, where we will inevitably break something in the conda configuration and then some developer will have to spend hours debugging and fixing it, and ask another developer to help out with another few hours. Unless there is significant user demand for conda packages, our precious developer time is better spend elsewhere.

**Comment by jamestwebber** [comment]
I'm workin' on it! Using guides from [conda](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html#) and [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html#).

Small-ish hiccups encountered so far (recording for posterity):
 - PyTorch goes by `torch` in pypi and `pytorch` in the conda ecosystem, so the automatic script failed there
   - the 1.5.2 release has a slightly malformed requirement  in setup.py: `'torch>=1.6<1.8'` (should have a comma between those) although it seems like pip doesn't care.
 - their script adds tests which just try to import every module. Because `funsor` is optional, that failed until I removed it from the list
   -  it is possible to run the real tests, but I'm not sure that's needed since they get run here. I believe conda-forge has limited CI time

Other than that things look to be working, at least on my machine. I believe the next step is to create a PR to https://github.com/conda-forge/staged-recipes

**Comment by jamestwebber** [comment]
Oh, also created pyro-ppl/pyro-api#21 so that the license file is included for that package. For now, I can include it in the recipe itself.

**Comment by jamestwebber** [comment]
🎉 https://github.com/conda-forge/staged-recipes/pull/14161
