### ISSUE TITLE
[FR] Iterable-style MCMC

### ISSUE THREAD

**Issue by SsnL** [pyro-ppl/pyro#1774]
### Issue Description

In many cases we want to use MCMC in an iterable-style, e.g., 
1. when the limiting factor is inference time, not number of iterations.
2. when we want to do post-processing on samples, in parallel to sampling.
3. when we want to update the MCMC progress on, say, a webpage.

**Comment by neerajprad** [comment]
I think this is also related to https://github.com/pyro-ppl/pyro/issues/1725. The MCMC class itself returns a generator, but the classes that drive it like `EmpiricalMarginal` eagerly call it for a fixed number of steps. It might be still possible for the users to do something like the following:

```python
mcmc = MCMC(kernel, num_samples = #large_num)._traces(*args, **kwargs)
while (..):
    trace = next(mcmc)
    # do something with trace
```

This is very hacky though, because the progress bar will look off and won't be cleaned up properly. The utility classes mentioned in #1725 are due a big refactor and we should provide a public method so that users can use the kernels generator style in a clean way.

**Comment by neerajprad** [comment]
Related to #1926; so we can track progress on that issue instead.
