### ISSUE TITLE
Question about the RuntimeError of ss_vae_M2.py

### ISSUE THREAD

**Issue by BeginnerAI** [pyro-ppl/pyro#1782]
- OS : windows 10
- Pytorch version: 1.0.0
- Pyro version: 0.3.1

Hi.
I have an interest in the ss_vae_m2 algorithm.
I make a run on the uploaded your code, but I met error messages as follows:

```
C:\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:53: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
Traceback (most recent call last):
  File "ss_vae_m2.py", line 427, in <module>
    main(args)
  File "ss_vae_m2.py", line 315, in main
    data_loaders = setup_data_loaders(MNISTCached, args.cuda, args.batch_size, sup_num=args.sup_num)
  File "D:\ss_vae\mnist_cached.py", line 221, in setup_data_loaders
    sup_num=sup_num, use_cuda=use_cuda)
  File "D:\ss_vae\mnist_cached.py", line 149, in __init__
    self.train_data = (transform(self.train_data.float()))
AttributeError: can't set attribute
about:blank#blocked
```
Could you take a look for this too? Thanks!

**Comment by Chechgm** [comment]
Hi @BeginnerAI,

I had the same problem not so long ago. My way to fix it was to change all calls to train_data, test_data, train_labels and test_labels to just data and targets. The model trains but I am not able to replicate Kingma's results. Let me know if it fixes your problem and if you are able to replicate their results.

Best,
Sergio

**Comment by neerajprad** [comment]
I think this is due to a recent change in `torchvision`. You might have to pin to `torchvision==0.2.1` to get it running. cc @jpchen who also faced this. We need to update the data loading utility class for SS-VAE to be compatible with the latest torchvision package or deprecate that dependency altogether. In the meantime, I think downgrading that dependency should work.
