### ISSUE TITLE
[discussion] Keeping subsample correlations in TracePredictive

### ISSUE THREAD

**Issue by ahmadsalim** [pyro-ppl/pyro#1858]
While developing #1854, I noticed that we do new random subsampling for each stochastic site in `TracePredictive` distribution. After reflecting about this, I have figured out that this might drop correlations between the sampled parameters under a subsampling statement.

I think what one needs to do is to fix a subset of random indices for each subsample site for all the sites. Any ideas on how one could this in a nice fashion?

My current idea is to create a dictionary when fixing the subsample sites, that map each subsample site to the set of random indices based on the provided subsample site size. Would this work?

Thank you in advance! 😄

**Comment by neerajprad** [comment]
You are right - I think your approach sounds the easiest and least intrusive. Another would be to add `indices` into `CondIndepStack`, but that is going to add a lot of data to the trace object.

You could keep a `subsampled_idxs` keyed by `cond_indep_frame.name`. As you iterate through a site's `cond_indep_stack`, you can check this dict for subsampled indices. If its present, use these, otherwise we call `torch.randint` to generate a random subsample and populate this dictionary. That way all sites will use the same set of indices for each frame. Does that sound reasonable? Let us take care of this in #1854 itself.

**Comment by ahmadsalim** [comment]
Sounds great, I have updated the PR 😄 !
