### ISSUE TITLE
Make potential energy function picklable

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#1929]
Related: #1930. To get multiprocessing to work correctly with the new API, we will need to make the potential function returned by `_pe_maker` to be picklable.

**Comment by fritzo** [comment]
`functools.partial` objects are picklable. I try to avoid locally defined functions whenever possible, since these pickling errors have plagued me in the past.

**Comment by neerajprad** [comment]
Thanks, that's what we need to do! Another source of pickling issue are poutines. A poutine wrapped model won't be picklable. I suppose the solution to that would be to wrap the model inside the function rather than passing in an already wrapped model.

**Comment by fritzo** [comment]
I believe the only issue with poutines is the local function `_wraps()` https://github.com/pyro-ppl/pyro/blob/cd4086b/pyro/poutine/messenger.py#L25
IIRC @eb8680 has previously tried very hard to make this a class and a `functools.partial` but was forced to make it a local function due to python subtleties.

**Comment by neerajprad** [comment]
Thanks for the context. You are right that the only issue there is `_wraps()`. I'll also take a look at this.
