### ISSUE TITLE
Bernoulli does not sample in the amount of batch_size

### ISSUE THREAD

**Issue by lundlab-kaltinel** [pyro-ppl/pyro#2750]
Hi,
I am trying to follow SS-VAE example of Pyro, and sample a 'y' from a Bernoulli distribution whenever my dataset does not have a label. However, Bernoulli does not sample.
In detail:
```py
  def guide(self,xs,ys=None):
    batch_size = xs.size(0)
    assert (batch_size == 20)
    if ys is None:
      with pyro.plate('nanopore',batch_size):
        assert (batch_size == 20)
        alpha = self.encoder_y.forward(xs) # we get the alpha from encoder_y
        print("alpha shape from the encoder_y", alpha.shape)
        ys = pyro.sample("y", dist.Bernoulli(alpha))
        m = dist.Bernoulli(alpha)
        print("Bernoulli event shape",m.event_shape)
        print("Bernoulli batch shape is",m.batch_shape)
        print("y from the encoder_y Bernoulli", ys.shape)
        print("y from the encoder_y Bernoulli is", ys)
```
And the output is:
```
alpha shape from the encoder_y torch.Size([20, 1])
Bernoulli event shape torch.Size([])
Bernoulli batch shape is torch.Size([20, 1])
y from the encoder_y Bernoulli torch.Size([2, 1])
y from the encoder_y Bernoulli is tensor([[0.],
        [1.]])
```
I wonder why` y `from the encoder_y Bernoulli has a shape of `([2, 1])` instead of `[20,1] `like `alpha`?

**Comment by eb8680** [comment]
Hi @lundlab-kaltinel, that's because Pyro is enumerating all possible values of `y` (i.e. 0 and 1) rather than sampling one value at a time.  Since those values are the same for each `y` in the `nanopore` plate they can be enumerated once and shared across the plate without duplication, so `y.shape == (2, 1)` instead of `(2, 20)`.  See [this section in the SSVAE example](http://pyro.ai/examples/ss-vae.html#Interlude:-Summing-Out-Discrete-Latents) for a mathematical explanation, and the [enumeration tutorial](http://pyro.ai/examples/enumeration.html) for an explanation of the tensor shapes generated by enumeration.

We're happy to help, but we ask that you use our [forum](https://forum.pyro.ai/) for any future questions so that the answers are more discoverable for others with similar questions. We use GitHub issues mostly for bug reports, feature requests and other development-related discussion.

**Comment by lundlab-kaltinel** [comment]
Thank you @eb8680.
I thought it is a bug of the sampler, therefore I thought of posting in here. Thank you for your explanation and redirection, I will post my case to the forum.
I understand your explanation and appreciate the tutorials. However I am still having problems with the Bernoulli sampler. I will continue to work on it with the help of forum.
