### ISSUE TITLE
`transforms` are not allowed when a `potential_fn()` is used [documentation][bug]

### ISSUE THREAD

**Issue by michaeldeistler** [pyro-ppl/pyro#2877]
### Issue Description
The [`transforms`](https://github.com/pyro-ppl/pyro/blob/373d348fe11963cd9a7d82b2b3099adf9345e1d5/pyro/infer/mcmc/hmc.py#L49) passed to e.g. `HMC` are not used when a `potential_fn` is passed (instead of a `model`). The transform is merged with the rest of the model [here](https://github.com/pyro-ppl/pyro/blob/373d348fe11963cd9a7d82b2b3099adf9345e1d5/pyro/infer/mcmc/util.py#L263), but this part of the code is never called when `model=None`. I'm not sure whether this is desired behavior or whether it's not implemented yet, but it should at least be mentioned in the docstring.

Even worse though: when `transforms` is specified, the samples are never transformed during sampling, but they are transformed back to unconstrained after sampling [here](https://github.com/pyro-ppl/pyro/blob/373d348fe11963cd9a7d82b2b3099adf9345e1d5/pyro/infer/mcmc/api.py#L462), leading to systematically wrong results.

Pyro version: 1.6.0

### Code Snippet
A brief wrapper around a transform allows to see that only the Inverse transform is called:
```python
from torch.distributions import SigmoidTransform
import pyro
import torch
import pyro.distributions as dist
from pyro.infer import HMC, MCMC

class DebugTF():
    def __init__(self, base_tf):
        self._base = base_tf
    
    def inv(self, theta):
        print("Inverse is called")
        return self._base.inv(theta)
    
    def log_abs_det_jacobian(self, *args, **kwargs):
        print("Jac")
        return self._base.log_abs_det_jacobian(*args, **kwargs)
        
    def __call__(self, theta):
        print("Forward")
        return self._base(theta)

transforms = DebugTF(SigmoidTransform().inv)

init_params = {"z": torch.tensor(0.)}
def potential_fn(params):
    return params["z"]

mcmc = MCMC(
    kernel=HMC(potential_fn=potential_fn),
    num_samples=10,
    warmup_steps=10,
    transforms={"z": transforms},
    initial_params=init_params)
mcmc.run()
```

This outputs only `Inverse is called` (the `log_abs_det_jacobian` and `__call__` are never called).

**Comment by fehiepsi** [comment]
Hi @michaeldeistler, the HMC kernel assumes that the variables have real supports (see [potential_fn doc](https://docs.pyro.ai/en/stable/mcmc.html#pyro.infer.mcmc.HMC)). If you want to perform transforms for those variables, I think you can define them in the `transforms` argument of [MCMC](https://docs.pyro.ai/en/stable/mcmc.html#pyro.infer.mcmc.api.MCMC).

**Comment by michaeldeistler** [comment]
Hi @fehiepsi 

Thanks for the response, and sorry for being unresponsive for a while. In my code snippet above, I pass the `transforms` to MCMC.:
```
mcmc = MCMC(
    kernel=HMC(potential_fn=potential_fn),
    ...
    transforms={"z": transforms},
)
```
Isn't this exactly what you suggested? As I describe above:

> When transforms is specified, the samples are never transformed during sampling, but they are transformed back to unconstrained after sampling here, leading to systematically wrong results.

When using a `model` instead of a `potential_fn`, things work fine.

**Comment by michaeldeistler** [comment]
Small aside, the same behavior happens when I pass the transforms to the HMC kernel directly:
```
mcmc = MCMC(
    kernel=HMC(
        potential_fn=potential_fn,
        transforms={"z": transforms},
    ),
    ...
)
```

**Comment by fehiepsi** [comment]
I think we should raise an error if `transforms` is passed to HMC together with `potential_fn` because the assumption is t

> The transform is merged with the rest of the model here, but this part of the code is never called when model=None.

Hmm, with `potential_fn`, the inputs are assumed to have real supports. I guess you want to use some sort of `AffineTransform` here (i.e. a map from `real` to `real`)? If so, maybe we need to clarify that `potential_fn` is the potential function with respect to its inputs (rather than its transformed inputs)?

> when transforms is specified, the samples are never transformed during sampling, but they are transformed back to unconstrained after sampling here, leading to systematically wrong results

I think this is the expected behavior. There is no need to perform transforming during sampling. First, we will get samples for inputs of `potential_fn`. Then we will perform extra transforms (inferred from `model` or specified by user) to transforms those samples to the constrained space. In MCMC, `transforms` is a "dictionary that specifies a transform for a sample site with constrained support to unconstrained space" so if you specify `transforms={"x": t}`, then
+ first, MCMC will collect samples of "unconstrained_x" (i.e. samples of `t(x)`)
+ then, MCMC will transform those "unconstrained_x" to "x", using `t.inv`

In your case, the transform is `t=DebugTF(SigmoidTransform().inv)`, so `t.inv` will be called (that explains why you get the message `This outputs only Inverse is called`) or `SigmoidTransform().inv.inv = SigmoidTransform()` will be called.

**Comment by michaeldeistler** [comment]
Oh, okey, I think I got it now! If I understand correctly, the `transforms` is the transform that was also applied to my `potential_fn` (outside of pyro) in order to make the support unconstrained. Thanks a lot for your explanations, that all makes sense!
