### ISSUE TITLE
gp.models.VariationalSparseGP and gp.models.vsgp.VariationalSparseGP

### ISSUE THREAD

**Issue by lbq8942** [pyro-ppl/pyro#2923]
may i ask what the difference between the two?i search gp.models.VariationalSparseGP in docs,i can't find,but it is used in the examples.

**Comment by eb8680** [comment]
Hi @lbq8942, `gp.models.VariationalSparseGP` is just an alias for `gp.models.vsgp.VariationalSparseGP`.

Please use our [forum](https://forum.pyro.ai/) for any future questions so that it's easier for other users to find them later. We mostly use GitHub issues for development-related topics like feature requests and bug reports.
