### ISSUE TITLE
Incorrect scale calculation for AutoMultivariateNormal

### ISSUE THREAD

**Issue by davidaknowles** [pyro-ppl/pyro#3232]
I could be wrong but I think the scale calculation for the AutoMultivariateNormal is incorrect. According to
https://docs.pyro.ai/en/stable/_modules/pyro/infer/autoguide/guides.html#AutoMultivariateNormal
it is `self.scale * self.scale_tril.diag()`. However, the scale should be the square root of the diagonal of the covariance, which would be something more like `(self.scale[..., None] * self.scale_tril)**2).sum(-1).sqrt()`. Note these are not equivalent since the latter depends on the off-diagonal elements of scale_tril whereas the former does not.

**Comment by martinjankowiak** [comment]
@davidaknowles can you clarify what you mean by incorrect? from what i recall, `scale` is just a parameter in a non-user-facing parameterization. nowhere is it claimed, e.g., that scale is a vector of marginal square root covariances. i guess your expectation is that it should be?

**Comment by martinjankowiak** [comment]
incidentally we use this parameterization because we found it tends to work quite a bit better than a vanilla `chol @ chol.T` (presumably because it reduces dependence on the ordering)

**Comment by martinjankowiak** [comment]
although i think you're right that the `_loc_scale` method may be implemented incorrectly (which feeds into e.g. the quantiles method)

**Comment by davidaknowles** [comment]
The parameterization seems very reasonable, but I would expect `scale` to correspond to the marginal for each variable (and presumably the marginal is what people expect from e.g. `quantiles`. I'm not sure what the current implementation corresponds to, maybe something like the standard deviation of the posterior for that variable conditioning on all other variables in the MVN (I don't think that's true even: it is the correct marginal calculation for the first variable in the MVN).

**Comment by fritzo** [comment]
@davidaknowles thanks for pointing this out.  This bug may have crept in as we changed parametrizations over the years.  IIRC the original `AutoMultivariateNormal` was nearly unusable due to poor parametrization.

I can add this to my TODO list: adding stricter tests for the internal `._loc_scale()` and fixing any bugs those tests witness.  I'm a little surprised the existing `.quantiles()` tests didn't catch these, so I can try tightening their tolerances and maybe add more correlated examples.

As @martinjankowiak commented, we do not think of `.scale` as user-facing and indeed offer no user-facing way to access scales beyond the `.quantiles()` method.  I'm still happy with this design choice of limited the interface, given the implicit nonlinear link functions chosen by `AutoContinuous` guides.  At least we could use a docstring warning that `.scale` is uninterpretable, but do let us know if you have ideas for a compelling non-foot-gun way to expose interpretable scales beyond `.quantiles()`.

**Comment by martinjankowiak** [comment]
ok i think i fixed this in #3233 (and added a regression test) but still need to double check if any other guides are affected or if we need to beef up the tests more
